baseURL = "https://rudra.dev/"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsStyle = "colorful"

paginate = 20

title = "Remy Wang"
theme = "flamingo"
[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "docs"

[params]
  author = "Rudra Narayan"
  description = "thoughts, obsessions and mostly rants"
  sitename = "Rudra Narayan Kar blog"
  github = "https://github.com/mrprofessor"
  twitter = "@weary_beard"
  favicon = "/images/favicon.ico"
  resume = "https://docs.google.com/gview?url=https://github.com/mrprofessor/resume/raw/master/rudra_narayan_resume.pdf&embedded=true"

# Projects list
[[params.projects]]
  name = "solitude"
  description = "A git based note taking application. 📚"
  demoLink = "https://solitudenote.github.io/solitude/"
  sourceLink = "https://github.com/solitudenote/solitude"


[[params.projects]]
  name = "gitkeeper"
  description = "A tiny microservice for client side GitHub authentication."
  demoLink = "https://solitudenote-gitkeeper.glitch.me/"
  sourceLink = "https://github.com/solitudenote/gitkeeper"


[[params.projects]]
  demoLink = ""
  sourceLink = "https://github.com/mrprofessor/obliterate"
  description = "A command line tool written in rust to replace rm."
  name = "obliterate"

[[params.projects]]
  demoLink = "https://rudra.dev/"
  sourceLink = "https://github.com/mrprofessor/rudra.dev"
  description = "Personal blog built using Org-mode and Hugo."
  name = "rudra.dev"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
