baseURL = "https://remy.wang/"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsStyle = "colorful"

paginate = 20

title = "Remy Wang"
theme = "flamingo"
[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "public"

[params]
  author = "Remy Wang"
  description = "research blog"
  sitename = "Remy Wang"
  github = "https://github.com/remysucre"
  # favicon = "/images/favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
